#!/usr/bin/env python2.7
from lxml import etree
import argparse
import csv
import sys
import argparse

def main(argv):
    print 'This is not implemented yet.'


try:
    parser = argparse.ArgumentParser(description='A utility for converting MechLaw CSV files into MechLaw XML files.')
    parser.add_argument('-f', metavar='csv_filename', required=True, help='input file in CSV format')
    args = parser.parse_args()

    main(sys.argv[1:])

except KeyboardInterrupt:
    quit(1)


